plugins {
    id('java')
    id('maven-publish')
}

repositories {
    maven { url "https://repo.viaversion.com"}
    maven { url "https://libraries.minecraft.net/" }
}
    
dependencies {
    compileOnly('com.viaversion:viaversion-api:4.9.3-SNAPSHOT')
    compileOnly('org.spigotmc:spigot-api:1.13.2-R0.1-SNAPSHOT')
    compileOnly('com.google.guava:guava:33.5.0-jre')
    compileOnly('com.mojang:authlib:1.5.21')
}

java {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId project.group
            artifactId project.name
            version project.version
            from components.java
        }
    }
}
