plugins {
    id('java')
}

repositories {
    maven { url "https://repo.viaversion.com"}
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'}
}
    
dependencies {
    compileOnly('com.viaversion:viaversion-api:4.9.3-SNAPSHOT')
    compileOnly 'org.spigotmc:spigot-api:1.13.2-R0.1-SNAPSHOT'
}

